project:
  type: website

website:
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual

execute: 
  freeze: auto